apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mynx-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mynx-deployment
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
